name: risuai

services:
  risuai:
    container_name: risuai
    build: .
    image: risuai-custom
    restart: always
    ports:
      - 38542:6001
    volumes:
      - risuai-save:/app/save

volumes:
  risuai-save:
